# Generated by Django 3.0.4 on 2020-03-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interview_date',
            field=models.CharField(choices=[('WED', '25(수)'), ('THUR', '26(목)'), ('FRI', '27(금)')], default='WED', max_length=20, verbose_name='희망 면접 날짜'),
        ),
    ]
